#!/bin/sh
# 
# Mapping /etc RW tmpfs and symlinking in flash etc files
#

JFFS2_FORMAT=y
JFFS2_MAGIC=0x1985
FLASHDEVICE=/dev/mtdblock3
FLASHTARGET=/flash

# Mirroring RO image to tmpfs
echo "FlashInit: Preparing tmpfs and flash-symlinked /etc and /root (RW)"

mkdir /tmp/etc
cp -a /etc/* /tmp/etc/
mount /tmp/etc /etc
# Removing  dropbear symlink, for etc-flash-link to work and be able to symlink files in that folder.
rm -rf /etc/dropbear

# Abort FLASH storage if /flash does not exist
if [[ ! -d /flash ]]; then 
        
        echo "FlashInit: $FLASHTARGET does not exist on rootfs, skipping symlinking of $FLASHTARGET/etc"
        exit
fi

# Check if flash is JFFS2 ready
MAGIC=$(head -c 2 $FLASHDEVICE | od -An -t u2 | awk '{ printf("0x%x",$1) }' )

# MAGIC FOUND - Trying to mount partition
if [[ $MAGIC = $JFFS2_MAGIC ]]; then
        echo "FlashInit: Mounting $FLASHDEVICE to $FLASHTARGET"
        mount -t jffs2 $FLASHDEVICE $FLASHTARGET

        if [[ ! $? -eq 0 ]]; then
                echo "FlashInit: Error mounting $FLASHDEVICE, recovery skipped."
                JFFS2_FORMAT=y
        fi
fi

if [[ JFFS2_FORMAT = y ]]; then
        echo "FlashInit: Formating $FLASHDEVICE and mounting to $FLASHTARGET"

        flash_eraseall -j /dev/mtd3
        mount -t jffs2 /dev/mtdblock3 $FLASHTARGET

        # Copy base structure
        mkdir $FLASHTARGET/etc
        cd /etc
        cp fw_env.config group hostname hosts passwd shadow profile $FLASHTARGET/etc/
                
        mkdir $FLASHTARGET/root
        cp -a /root $FLASHTARGET/root
        mount $FLASHTARGET/root /root        
         
        # prepare dropbear hostkey in flash
        mkdir $FLASHTARGET/etc/dropbear
        dropbearkey -t ecdsa -f $FLASHTARGET/etc/dropbear/dropbear_ecdsa_host_key
        


fi
  
echo "FlashInit: Symlinking $FLASHTARGET/etc (etc-flash-symlink.sh)"
/bin/etc-flash-symlink.sh

echo "FlashInit: Executing $FLASHTARGET/init.sh"
# Run flash init.sh if it exists 
[ ! -f $FLASHTARGET/init.sh ] && echo -e "#!/bin/sh\n# Place init logic here\n\n" > $FLASHTARGET/init.sh && chmod a+x $FLASHTARGET/init.sh
[ -f $FLASHTARGET/init.sh ] && $FLASHTARGET/init.sh 




