#!/bin/sh
# 
# Mapping /etc RW tmpfs and symlinking in flash etc files
#

# Mirroring RO image to tmpfs
mkdir /tmp/etc
cp -a /etc/* /tmp/etc/
mount /tmp/etc /etc

# FLASH: Preparing Volume
flash=$(stat -f /dev/mtd3 | grep Type | grep tmpfs)
if [[ $? != 0 ]]; then
        echo "mtdblock3: Creating new JFFS2 volume"

        flash_eraseall -j /dev/mtd3
        mount -t jffs2 /dev/mtdblock3 /flash

        # copy base structure
        mkdir /flash/etc
        cd /etc
        cp fw_env.config group hostname hosts passwd shadow profile /flash/etc/

else

        echo "mtdblock3: Mounting existing JFFS2 volume"
        mount -t jffs2 /dev/mtdblock3 /flash
fi


# FLASH: Symlinking flash etc files to /etc - for that persistent touch.
/bin/etc-flash-link.sh

# Run flash init.sh if it exists 
[ ! -f /flash/init.sh ] && echo -e "#!/bin/sh\n# Place init logic here\n\n" > /flash/init.sh && chmod a+x /flash/init.sh
[ -f /flash/init.sh ] && /flash/init.sh 

# starting telnetd for now. dropbear later.
telnetd &



